### ISSUE TITLE
Looking for support to install and begin using

### ISSUE THREAD

**Issue by PalmerRobbie** [PokerFacowaty/stash-qmt#1]
Hello. I followed all of the instructions in the Read Me, but nothing has happened in my Stash app. What is the last action step I need to do, before I see the windows you included as your screenshots? Do I need to click "Reload Plugins" in the Stash gui? Do I need to run the  stash-qmt.py file using the Python interpreter I installed?

I've installed Python and all the dependencies and system variables, but I'm not seeing anything. Please provide some insight I could have missed. Thank You

**Comment by PalmerRobbie** [comment]
Hello again. I just figured out I don't think your application (the python file) is running, it gets some kind of error. Here is the output, I can't sort out what the issue could be. Like I said I followed everything in your ReadMe instructions. Any insight would be greatly appreciated. My Stash is on v0.23.1
**************************************************************************************************************************************



C:\Users\paper\.stash\Plugins\stash-qmt-0.1.0>py stash-qmt.py
Traceback (most recent call last):
  File "C:\Users\paper\.stash\Plugins\stash-qmt-0.1.0\stash-qmt.py", line 195, in <module>
    parse_yaml()
  File "C:\Users\paper\.stash\Plugins\stash-qmt-0.1.0\stash-qmt.py", line 41, in parse_yaml
    ids_tags = get_tag_ids(cfg["Templates"][tmpl])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\.stash\Plugins\stash-qmt-0.1.0\stash-qmt.py", line 79, in get_tag_ids
    result[int(tag_id)] = tag_name
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by PalmerRobbie** [comment]
Hello again again. After stumbling and playing around with this, I got it going. The instructions put a lot of burden on the user to make assumptions and be experienced with this kind of multi-faceted install and configuration, in my opinion. I would have appreciated a little bit more enumeration. But thanks for the build!
